import 'package:animation_wrappers/animations/faded_scale_animation.dart';
import 'package:auto_route/auto_route.dart';
import 'package:bloc_revisions/core/constants/my_assets.dart';
import 'package:bloc_revisions/core/constants/my_colors.dart';
import 'package:bloc_revisions/data/repositories/repository.dart';
import 'package:bloc_revisions/presentation/screens/auth/general/home/home_model.dart';
import 'package:bloc_revisions/presentation/screens/router/router_imports.gr.dart';
import 'package:feather_icons/feather_icons.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:velocity_bloc/velocity_bloc.dart';
import 'package:velocity_x/velocity_x.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter_widget_from_html_core/flutter_widget_from_html_core.dart';

part 'home.dart';
part 'home_view_model.dart';
part 'home_details.dart';
